{
 "title": "Chrony",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(chrony_up,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(chrony_up{hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Chrony status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chrony_leap_status{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "leap status"
    }
   ]
  },
  {
   "title": "Chrony Up/Down - ${hostname}",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "chrony_up{hostname=\"${hostname}\",instance=\"${instance}\"} == bool 1",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Chrony last update - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_clock_last_update_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "last update"
    }
   ]
  },
  {
   "title": "Chrony stratum - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "chrony_clock_stratum{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "stratum"
    }
   ]
  },
  {
   "title": "Chrony clock skew - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "chrony_clock_skew_ppm{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "skew"
    }
   ]
  },
  {
   "title": "Chrony frequency error - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "chrony_frequency_error_ppm{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "frequency error"
    }
   ]
  },
  {
   "title": "Chrony root delay - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_root_delay_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "root delay"
    }
   ]
  },
  {
   "title": "Chrony root dispersion - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_root_dispersion_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "root dispersion"
    }
   ]
  },
  {
   "title": "Chrony time offset - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_time_offset_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "offset estimated"
    },
    {
     "expr": "chrony_time_offset_rms_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "offset rms"
    },
    {
     "expr": "chrony_time_offset_ntp_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "offset ntp"
    }
   ]
  },
  {
   "title": "Chrony  updates - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(chrony_time_ref_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "updates"
    }
   ]
  },
  {
   "title": "Chrony  leap status - ${hostname} - ${instance}",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "chrony_leap_status{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Chrony source clock last measurement - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_source_clock_last_measurement_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Chrony  source clock mode - ${hostname} - ${instance}",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "chrony_source_clock_mode{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Chrony  source clock state - ${hostname} - ${instance}",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "chrony_source_clock_state{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Chrony source clock reachability - ${hostname} - ${instance}",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "chrony_source_clock_reachability{hostname=\"${hostname}\",instance=\"${instance}\"} == bool  255",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Chrony source frecuency error - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "chrony_source_frequency_error_ppm{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Chrony source stratum - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "chrony_source_clock_stratum{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Chrony source time offset - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_source_time_offset_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}