{
 "title": "CPU Linux",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(system_uname_info{sysname=\"Linux\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage % - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"interrupt\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Interrupt"
    },
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"steal\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})\n",
     "legendFormat": "Steal"
    },
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"softirq\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})\n",
     "legendFormat": "Softirq"
    },
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"system\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "System"
    },
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"user\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "User"
    },
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"nice\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Nice"
    },
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"wait\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Wait"
    }
   ]
  },
  {
   "title": "Cpu usage % per core - ${hostname}",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "clamp(100 - (sum(irate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=~\"idle|wait\"}[$__rate_interval])) without (state) * 100 ), 1e-7, 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU User usage % - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"user\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Cpu User usage % per core - ${hostname}",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "clamp(sum(irate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=\"user\"}[$__rate_interval])) without (state) * 100 , 1e-7, 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU System usage % - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"system\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Cpu System usage % per core - ${hostname}",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "clamp(sum(irate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=\"system\"}[$__rate_interval])) without (state) * 100 , 1e-7, 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Nice usage % - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"nice\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Nice"
    }
   ]
  },
  {
   "title": "Cpu Nice usage % per core - ${hostname}",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "clamp(sum(irate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=\"nice\"}[$__rate_interval])) without (state) * 100 , 1e-7, 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU SoftIrq usage % - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"softirq\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Softirq"
    }
   ]
  },
  {
   "title": "Cpu Softirq usage % per core - ${hostname}",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "clamp(sum(irate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=\"softirq\"}[$__rate_interval])) without (state) * 100 , 1e-7, 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Wait usage % - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"wait\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Wait"
    }
   ]
  },
  {
   "title": "Cpu Wait usage % per core - ${hostname}",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "clamp(sum(irate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=\"wait\"}[$__rate_interval])) without (state) * 100 , 1e-7, 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Interrupt usage % - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"interrupt\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Interrupt"
    }
   ]
  },
  {
   "title": "Cpu Interrupt usage % per core - ${hostname}",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "clamp(sum(irate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=\"interrupt\"}[$__rate_interval])) without (state) * 100 , 1e-7, 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Steal usage % - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"steal\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Steal"
    }
   ]
  },
  {
   "title": "Cpu Steal usage % per core - ${hostname}",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "clamp(sum(irate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=\"steal\"}[$__rate_interval])) without (state) * 100 , 1e-7, 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  }
 ]
}