{
 "title": "HAProxy Backends",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(haproxy_up,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(haproxy_up{hostname=\"$hostname\"},instance)"
    }
   },
   {
    "name": "proxy",
    "label": "backend",
    "query": {
     "query": "label_values(haproxy_backend_status{hostname=\"$hostname\", instance=\"$instance\"},proxy)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HAproxy  Backend Status - ${hostname} - ${instance} - ${proxy}",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "MIN without (haproxy_backend_status)(haproxy_backend_status{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",haproxy_backend_status=\"DOWN\"} * 1)+ MIN without (haproxy_backend_status)(haproxy_backend_status{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",haproxy_backend_status=\"UP\"} * 2)",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "HAproxy Backend Queue - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}",
     "legendFormat": "queue"
    }
   ]
  },
  {
   "title": "HAproxy Backend Current Sessions - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "HAproxy Backend In/Out Bytes - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(haproxy_backend_bytes_in_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "In"
    },
    {
     "expr": "irate(haproxy_backend_bytes_out_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "HAproxy Backend responses/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "irate(haproxy_backend_http_responses_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HAProxy Backend SSL Sessions/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "irate(haproxy_backend_ssl_sessions_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "ssl sessions/s"
    },
    {
     "expr": "irate(haproxy_backend_ssl_reused_sessions_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "ssl reuse sessions/s"
    }
   ]
  },
  {
   "title": "HAproxy  Backend SSL Handshake/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "irate(haproxy_backend_ssl_failed_handshake_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "Failed handshake/s"
    }
   ]
  },
  {
   "title": "HAProxy Backend connections/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "irate(haproxy_backend_connections_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "connections/s"
    },
    {
     "expr": "irate(haproxy_backend_denied_connections_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "denied connections/s"
    }
   ]
  },
  {
   "title": "HAproxy  Failed SSL Handshake/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "irate(haproxy_frontend_ssl_failed_handshake_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "Failed handshake/s"
    }
   ]
  }
 ]
}