{
 "title": "Nfsd",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(system_nfsd_requests_total,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "nfsd server threads - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_nfsd_server_threads{hostname=\"${hostname}\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "nfsd stale file handles - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_nfsd_file_handles_stale_total{hostname=\"${hostname}\"}[$__rate_interval]",
     "legendFormat": "file handles stale"
    }
   ]
  },
  {
   "title": "nfsd packets - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_nfsd_packets_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{protocol}} packets/s"
    }
   ]
  },
  {
   "title": "nfsd tcp connections/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_nfsd_connections_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "tcp connections/s"
    }
   ]
  },
  {
   "title": "nfsd rpc calls/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_nfsd_server_rpc_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "rpc calls/s"
    }
   ]
  },
  {
   "title": "nfsd rpc errors/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_nfsd_rpc_errors_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{error}} errors/s"
    }
   ]
  },
  {
   "title": "nfsd requests/s v3 - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_nfsd_requests_total{hostname=\"${hostname}\",proto=\"3\"}[$__rate_interval])",
     "legendFormat": "{{method}} request/s"
    }
   ]
  },
  {
   "title": "nfsd requests/s v4 - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_nfsd_requests_total{hostname=\"${hostname}\",proto=\"4\"}[$__rate_interval])",
     "legendFormat": "{{method}} request/s"
    }
   ]
  },
  {
   "title": "nfsd cache - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_nfsd_reply_cache_hits_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "hits/s"
    },
    {
     "expr": "irate(system_nfsd_reply_cache_misses_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "misses/s"
    },
    {
     "expr": "irate(system_nfsd_reply_cache_nocache_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "nocache/s"
    }
   ]
  },
  {
   "title": "nfsd disk - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(system_nfsd_disk_bytes_read_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "read bytes/s"
    },
    {
     "expr": "irate(system_nfsd_disk_bytes_written_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "written bytes/s"
    }
   ]
  },
  {
   "title": "nfsd read-ahead cache size - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_nfsd_read_ahead_cache_size_blocks{hostname=\"${hostname}\"}[$__rate_interval]",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "nfsd read-ahead cache not founds - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_nfsd_read_ahead_cache_not_found{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "not founds/s"
    }
   ]
  }
 ]
}