{
 "title": "Postgresql table",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(pg_up,hostname)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{hostname=\"$hostname\"},instance)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(pg_table_size_bytes{hostname=\"$hostname\", instance=\"$instance\"},database)"
    }
   },
   {
    "name": "schema",
    "query": {
     "query": "label_values(pg_table_size_bytes{hostname=\"$hostname\", instance=\"$instance\", database=\"$database\"},schema)"
    }
   },
   {
    "name": "table",
    "query": {
     "query": "label_values(pg_table_size_bytes{hostname=\"$hostname\", instance=\"$instance\", database=\"$database\", schema=\"$schema\"},table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last analyze - ${database} - ${schema} - ${table}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-pg_table_last_analyze_seconds{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last autoanalyze - ${database} - ${schema} - ${table}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-pg_table_last_autoanalyze_seconds{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last autovacuum - ${database} - ${schema} - ${table}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-pg_table_last_autovacuum_seconds{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last index scan - ${database} - ${schema} - ${table}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-pg_table_last_idx_scan_seconds{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last sequential scan - ${database} - ${schema} - ${table}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-pg_table_last_seq_scan_seconds{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last vacuum - ${database} - ${schema} - ${table}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-pg_table_last_vacuum_seconds{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table size - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_table_size_bytes{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "{{database}} - {{schema}} - {{table}}"
    }
   ]
  },
  {
   "title": "Table indexes size - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_table_indexes_size_bytes{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "{{database}} - {{schema}} - {{table}}"
    }
   ]
  },
  {
   "title": "Table heap read blocks - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_heap_read_blocks_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Table heap hit blocks - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_heap_hit_blocks_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Table idx read blocks - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_idx_read_blocks_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Table idx hit blocks - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_idx_hit_blocks_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Table toads read  blocks - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_toast_read_blocks_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Table toast hit blocks - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_toast_hit_blocks_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Table tidx read blocks - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_tidx_read_blocks_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Table tidx hit blocks - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_tidx_hit_blocks_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Table modified rows - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_inserted_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "inserted"
    },
    {
     "expr": "irate(pg_table_updated_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "updated"
    },
    {
     "expr": "irate(pg_table_deleted_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "Table dead/live rows - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_table_dead_rows{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "dead"
    },
    {
     "expr": "pg_table_live_rows{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "live"
    }
   ]
  },
  {
   "title": "Table updated rows - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_hot_updated_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "hot updates"
    },
    {
     "expr": "irate(pg_table_newpage_updated_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "newpage updates"
    }
   ]
  },
  {
   "title": "Table maintenance actions - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_vacuum_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "vacuum"
    },
    {
     "expr": "irate(pg_table_autovacuum_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "autovacuum"
    },
    {
     "expr": "irate(pg_table_analyze_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "analyze"
    },
    {
     "expr": "irate(pg_table_autoanalyze_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "autoanalyze"
    }
   ]
  },
  {
   "title": "Table inserted rows since last vacuum - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_table_inserted_since_vacuum_rows{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "inserted rows"
    }
   ]
  },
  {
   "title": "Table modified rows since last analyze - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_table_modified_since_analyze_rows{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}",
     "legendFormat": "modified rows"
    }
   ]
  },
  {
   "title": "Table sequential scans - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_seq_scan_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "sequential scans"
    }
   ]
  },
  {
   "title": "Table rows read in sequential scans - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_seq_read_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "Table indexes scans - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_idx_scan_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "indexes scans"
    }
   ]
  },
  {
   "title": "Table row fetched in indexes scans - ${hostname} - ${instance} - ${database} - ${schema} - ${table}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "irate(pg_table_idx_fetch_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=\"${database}\",schema=\"${schema}\",table=\"${table}\"}[$__rate_interval])",
     "legendFormat": "rows"
    }
   ]
  }
 ]
}