{
 "title": "Postgresql database",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(pg_up,hostname)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{hostname=\"$hostname\"},instance)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(pg_database_backends{hostname=\"$hostname\", instance=\"$instance\"},database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Database backends - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_database_backends{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database max transaction time - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_activity_max_tx_seconds{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}",
     "legendFormat": "{{database}} - {{state}}"
    }
   ]
  },
  {
   "title": "Database connections activity - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_activity_connections{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}",
     "legendFormat": "{{database}} - {{state}}"
    }
   ]
  },
  {
   "title": "Database commits/rollbacks - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "xact/s" } },
   "targets": [
    {
     "expr": "irate(pg_database_xact_commit_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - commits"
    },
    {
     "expr": "irate(pg_database_xact_rollback_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - rollbacks"
    }
   ]
  },
  {
   "title": "Database size - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database rows - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "tuples/s" } },
   "targets": [
    {
     "expr": "irate(pg_database_returned_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - returned"
    },
    {
     "expr": "irate(pg_database_fetched_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - feched"
    },
    {
     "expr": "irate(pg_database_inserted_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - inserted"
    },
    {
     "expr": "irate(pg_database_updated_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - updated"
    },
    {
     "expr": "irate(pg_database_deleted_rows_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - deleted"
    }
   ]
  },
  {
   "title": "Database blocks Read/Hit - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "blocks/s" } },
   "targets": [
    {
     "expr": "irate(pg_database_blks_read_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - reads"
    },
    {
     "expr": "irate(pg_database_blks_hit_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - hits"
    }
   ]
  },
  {
   "title": "Database temp bytes/s - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pg_database_temp_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database temp files - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "files/s" } },
   "targets": [
    {
     "expr": "irate(pg_database_temp_files_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database deadlocks - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "deadlocks/s" } },
   "targets": [
    {
     "expr": "irate(pg_database_deadlocks_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database locks - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_database_locks{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}",
     "legendFormat": "{{database}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Database read Time - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_database_blk_read_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database conflits - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "queries/s" } },
   "targets": [
    {
     "expr": "irate(pg_database_conflicts_tablespace_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - tablespace"
    },
    {
     "expr": "irate(pg_database_conflicts_lock_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - lock"
    },
    {
     "expr": "irate(pg_database_conflicts_snapshot_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - snapshot"
    },
    {
     "expr": "irate(pg_database_conflicts_bufferpin_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - bufferpin"
    },
    {
     "expr": "irate(pg_database_conflicts_deadlock_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - deadlock"
    }
   ]
  },
  {
   "title": "Database sessions - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "sessions/s" } },
   "targets": [
    {
     "expr": "irate(pg_database_sessions_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - sessions"
    },
    {
     "expr": "irate(pg_database_sessions_abandoned_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - abandoned"
    },
    {
     "expr": "irate(pg_database_sessions_fatal_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - fatal"
    },
    {
     "expr": "irate(pg_database_sessions_killed_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}} - killed"
    }
   ]
  },
  {
   "title": "Database write time - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_database_blk_write_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database session time - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_database_session_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database active time - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_database_active_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database idle in transaction time - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_database_idle_in_transaction_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\",database=~\"${database}\"}[$__rate_interval])",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}