{
 "title": "Postfix",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(postfix_queue_size,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(postfix_queue_size{hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Postfix queue size - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "postfix_queue_size{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Postfix delivered to virtual mailbox - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(postfix_virtual_delivered_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "virutal delivered/s"
    }
   ]
  },
  {
   "title": "Postfix messages cleanup - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "irate(postfix_cleanup_messages_not_accepted_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "not accepted/s"
    },
    {
     "expr": "irate(postfix_cleanup_messages_rejected_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "rejected/s"
    },
    {
     "expr": "irate(postfix_cleanup_messages_processed_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "processed/s"
    }
   ]
  }
 ]
}