{
 "title": "System AIX",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(system_uname_info{sysname=\"AIX\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime_seconds{hostname=\"${hostname}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load_1m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "system_load_5m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "system_load_15m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_processes_state{hostname=\"${hostname}\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "system_processes_state{hostname=\"${hostname}\",state=\"running\"}",
     "legendFormat": "running"
    },
    {
     "expr": "system_processes_state{hostname=\"${hostname}\",state=\"sleeping\"}",
     "legendFormat": "sleeping"
    },
    {
     "expr": "system_processes_state{hostname=\"${hostname}\",state=\"stopped\"}",
     "legendFormat": "stopped"
    },
    {
     "expr": "system_processes_state{hostname=\"${hostname}\",state=\"zombies\"}",
     "legendFormat": "zombies"
    }
   ]
  },
  {
   "title": "Filesystem space usage - ${hostname}",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_df_used_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_df_free_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_df_reserved_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - sum(irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=~\"idle|wait\"}[$__rate_interval])) without (state) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Busy"
    },
    {
     "expr": "sum(irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=~\"user\"}[$__rate_interval])) without (state) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "User"
    },
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"system\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "System"
    },
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"wait\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Wait"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_used_bytes{hostname=\"${hostname}\"}+system_memory_free_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "system_memory_used_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "system_memory_free_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "LPAR physical cpu",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "system_lpar_entitled{hostname=\"${hostname}\"}",
     "legendFormat": "entitled"
    },
    {
     "expr": "system_lpar_system{hostname=\"${hostname}\"}",
     "legendFormat": "system"
    },
    {
     "expr": "system_lpar_user{hostname=\"${hostname}\"}",
     "legendFormat": "user"
    },
    {
     "expr": "system_lpar_wait{hostname=\"${hostname}\"}",
     "legendFormat": "wait"
    },
    {
     "expr": "system_lpar_idle{hostname=\"${hostname}\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Cpu usage % per core - ${hostname}",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "clamp(100 - (sum(irate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=~\"idle|wait\"}[$__rate_interval])) without (state) * 100 ), 1e-7, 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "system_load_1m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "system_load_5m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "system_load_15m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Processes state - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "system_processes_state{hostname=\"${hostname}\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Processes Forks/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "forks/s" } },
   "targets": [
    {
     "expr": "irate(system_processes_forks_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "forks"
    }
   ]
  },
  {
   "title": "Processes Context switches - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ctxt/s" } },
   "targets": [
    {
     "expr": "irate(system_processes_contextswitch_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Swap usage - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_swap_used_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "system_swap_cached_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "system_swap_free_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap IO bytes/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(system_swap_in_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "Swap in bytes/s"
    },
    {
     "expr": "irate(system_swap_out_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "Swap out bytes/s"
    }
   ]
  },
  {
   "title": "Memory usage - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_slab_reclaimable_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Slab reclaimable"
    },
    {
     "expr": "system_memory_slab_unreclaimable_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Slab unreclaimable"
    },
    {
     "expr": "system_memory_used_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "system_memory_buffers_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "system_memory_cached_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "system_memory_free_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Tcp connections - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "system_tcp_connections{hostname=\"${hostname}\",port=\"all\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Filesystem space usage  % - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_df_used_bytes{hostname=\"${hostname}\"}*100/(system_df_free_bytes{hostname=\"${hostname}\"}+system_df_used_bytes{hostname=\"${hostname}\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem inode usage % - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_df_used_inodes{hostname=\"${hostname}\"}*100/(system_df_free_inodes{hostname=\"${hostname}\"}+system_df_used_inodes{hostname=\"${hostname}\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Interface rx bytes/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(system_interface_rx_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Interface tx bytes/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(system_interface_tx_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Interface rx packets/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "pkt/s" } },
   "targets": [
    {
     "expr": "irate(system_interface_rx_packets_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Interface tx packets/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "pkt/s" } },
   "targets": [
    {
     "expr": "irate(system_interface_tx_packets_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Interface rx errors - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "delta(system_interface_rx_errors_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Interface tx errors - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "delta(system_interface_tx_errors_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Disk read bytes/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(system_disk_read_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk write bytes/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(system_disk_write_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk read IO/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "io/s" } },
   "targets": [
    {
     "expr": "irate(system_disk_read_ops_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk write IO/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "io/s" } },
   "targets": [
    {
     "expr": "irate(system_disk_write_ops_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk average read time  - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(system_disk_read_weighted_time_seconds_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk average write time  - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(system_disk_write_weighted_time_seconds_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}