{
 "title": "System Linux",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(system_uname_info{sysname=\"Linux\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime_seconds{hostname=\"${hostname}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load_1m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "system_load_5m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "system_load_15m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_processes_state{hostname=\"${hostname}\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "system_processes_state{hostname=\"${hostname}\",state=\"running\"}",
     "legendFormat": "running"
    },
    {
     "expr": "system_processes_state{hostname=\"${hostname}\",state=\"sleeping\"}",
     "legendFormat": "sleeping"
    },
    {
     "expr": "system_processes_state{hostname=\"${hostname}\",state=\"stopped\"}",
     "legendFormat": "stopped"
    },
    {
     "expr": "system_processes_state{hostname=\"${hostname}\",state=\"zombies\"}",
     "legendFormat": "zombies"
    }
   ]
  },
  {
   "title": "Filesystem space usage - ${hostname}",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_df_used_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_df_free_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_df_reserved_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - sum(irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=~\"idle|wait\"}[$__rate_interval])) without (state) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Busy"
    },
    {
     "expr": "sum(irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=~\"user|nice\"}[$__rate_interval])) without (state) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "User + Nice"
    },
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"system\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "System"
    },
    {
     "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"wait\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
     "legendFormat": "Wait"
    }
   ]
  },
  {
   "title": "OOM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_vm_oom_kill_total{hostname=\"${hostname}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_used_bytes{hostname=\"${hostname}\"}+system_memory_free_bytes{hostname=\"${hostname}\"}+system_memory_buffers_bytes{hostname=\"${hostname}\"}+system_memory_cached_bytes{hostname=\"${hostname}\"}+system_memory_slab_reclaimable_bytes{hostname=\"${hostname}\"}+system_memory_slab_unreclaimable_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "system_memory_used_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "system_memory_free_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "system_memory_cached_bytes{hostname=\"${hostname}\"}+system_memory_buffers_bytes{hostname=\"${hostname}\"}",
     "legendFormat": "Buff/Cache"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage % - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"interrupt\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
       "legendFormat": "Interrupt"
      },
      {
       "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"steal\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})\n",
       "legendFormat": "Steal"
      },
      {
       "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"softirq\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})\n",
       "legendFormat": "Softirq"
      },
      {
       "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"system\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
       "legendFormat": "System"
      },
      {
       "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"user\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
       "legendFormat": "User"
      },
      {
       "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"nice\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
       "legendFormat": "Nice"
      },
      {
       "expr": "irate(system_cpu_all_usage_seconds_total{hostname=\"${hostname}\",state=\"wait\"}[$__rate_interval]) * 100 / scalar(system_cpu_count{hostname=\"${hostname}\"})",
       "legendFormat": "Wait"
      }
     ]
    },
    {
     "title": "Cpu usage % per core - ${hostname}",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "clamp(100 - (sum(irate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=~\"idle|wait\"}[$__rate_interval])) without (state) * 100 ), 1e-7, 100)",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "Load - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "system_load_1m{hostname=\"${hostname}\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "system_load_5m{hostname=\"${hostname}\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "system_load_15m{hostname=\"${hostname}\"}",
       "legendFormat": "Load 15m"
      }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pressure waiting - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(system_pressure_cpu_waiting_seconds_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "CPU"
      },
      {
       "expr": "irate(system_pressure_memory_waiting_seconds_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "Memory"
      },
      {
       "expr": "irate(system_pressure_io_waiting_seconds_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "IO"
      }
     ]
    },
    {
     "title": "Pressure stalled - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(system_pressure_memory_stalled_seconds_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "Memory"
      },
      {
       "expr": "irate(system_pressure_io_stalled_seconds_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "IO"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes Forks/s - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "forks/s" } },
     "targets": [
      {
       "expr": "irate(system_processes_forks_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "forks"
      }
     ]
    },
    {
     "title": "Processes state - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "system_processes_state{hostname=\"${hostname}\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Processes Context switches - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ctxt/s" } },
     "targets": [
      {
       "expr": "irate(system_processes_contextswitch_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "context switches"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "system_memory_used_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "system_memory_available_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Memory usage detail - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "system_memory_slab_reclaimable_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Slab reclaimable"
      },
      {
       "expr": "system_memory_slab_unreclaimable_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Slab unreclaimable"
      },
      {
       "expr": "system_memory_buffers_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Buffers"
      },
      {
       "expr": "system_memory_cached_bytes{hostname=\"${hostname}\"}-system_memory_shared_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Cached"
      },
      {
       "expr": "system_memory_shared_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Shared"
      },
      {
       "expr": "system_memory_page_tables_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Page Tables"
      },
      {
       "expr": "system_memory_kernel_stack_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Kernel Stack"
      },
      {
       "expr": "system_memory_anonymous_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Anonymous"
      },
      {
       "expr": "system_memory_swap_cached_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Swap cached"
      },
      {
       "expr": "system_memory_hugepages_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Hugepages"
      },
      {
       "expr": "system_memory_vmalloc_used_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Vmalloc"
      },
      {
       "expr": "system_memory_free_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "system_memory_total_bytes{hostname=\"${hostname}\"}-system_memory_free_bytes{hostname=\"${hostname}\"}-system_memory_slab_reclaimable_bytes{hostname=\"${hostname}\"}-system_memory_slab_unreclaimable_bytes{hostname=\"${hostname}\"}-system_memory_buffers_bytes{hostname=\"${hostname}\"}-system_memory_cached_bytes{hostname=\"${hostname}\"}-system_memory_page_tables_bytes{hostname=\"${hostname}\"}-system_memory_kernel_stack_bytes{hostname=\"${hostname}\"}-system_memory_anonymous_bytes{hostname=\"${hostname}\"}-system_memory_swap_cached_bytes{hostname=\"${hostname}\"}-system_memory_hugepages_bytes{hostname=\"${hostname}\"}-system_memory_vmalloc_used_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Untracked"
      }
     ]
    },
    {
     "title": "Memory Active/Inactive - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "system_memory_slab_reclaimable_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Slab reclaimable"
      },
      {
       "expr": "system_memory_slab_unreclaimable_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Slab unreclaimable"
      },
      {
       "expr": "system_memory_active_anonymous_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Active Anonymous"
      },
      {
       "expr": "system_memory_inactive_anonymous_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Inactive Anonymous"
      },
      {
       "expr": "system_memory_active_page_cache_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Active Page Cache"
      },
      {
       "expr": "system_memory_inactive_page_cache_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Inactive Page Cache"
      },
      {
       "expr": "system_memory_page_tables_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Page Tables"
      },
      {
       "expr": "system_memory_kernel_stack_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Kernel Stack"
      },
      {
       "expr": "system_memory_swap_cached_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Swap cached"
      },
      {
       "expr": "system_memory_hugepages_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Hugepages"
      },
      {
       "expr": "system_memory_vmalloc_used_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Vmalloc"
      },
      {
       "expr": "system_memory_free_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "system_memory_total_bytes{hostname=\"${hostname}\"}-system_memory_free_bytes{hostname=\"${hostname}\"}-system_memory_slab_reclaimable_bytes{hostname=\"${hostname}\"}-system_memory_slab_unreclaimable_bytes{hostname=\"${hostname}\"}-system_memory_active_anonymous_bytes{hostname=\"${hostname}\"}-system_memory_inactive_anonymous_bytes{hostname=\"${hostname}\"}-system_memory_active_page_cache_bytes{hostname=\"${hostname}\"}-system_memory_inactive_page_cache_bytes{hostname=\"${hostname}\"}-system_memory_page_tables_bytes{hostname=\"${hostname}\"}-system_memory_kernel_stack_bytes{hostname=\"${hostname}\"}-system_memory_swap_cached_bytes{hostname=\"${hostname}\"}-system_memory_hugepages_bytes{hostname=\"${hostname}\"}-system_memory_vmalloc_used_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Untracked"
      }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swap usage - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "system_swap_used_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "system_swap_cached_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Cached"
      },
      {
       "expr": "system_swap_free_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Swap IO bytes/s - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(system_swap_in_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "Swap in bytes/s"
      },
      {
       "expr": "irate(system_swap_out_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "Swap out bytes/s"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tcp connections - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "system_tcp_all_connections{hostname=\"${hostname}\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space usage  % - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "system_df_used_bytes{hostname=\"${hostname}\"}*100/(system_df_free_bytes{hostname=\"${hostname}\"}+system_df_used_bytes{hostname=\"${hostname}\"})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem space usage - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "system_df_used_bytes{hostname=\"${hostname}\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem inode usage % - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "system_df_used_inodes{hostname=\"${hostname}\"}*100/(system_df_free_inodes{hostname=\"${hostname}\"}+system_df_used_inodes{hostname=\"${hostname}\"})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem inode usage - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_df_used_inodes{hostname=\"${hostname}\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface rx bytes/s - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(system_interface_rx_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Interface tx bytes/s - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(system_interface_tx_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Interface rx packets/s - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(system_interface_rx_packets_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Interface tx packets/s - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(system_interface_tx_packets_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Interface rx errors - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "errors" } },
     "targets": [
      {
       "expr": "delta(system_interface_rx_errors_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Interface tx errors - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "errors" } },
     "targets": [
      {
       "expr": "delta(system_interface_tx_errors_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read bytes/s - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(system_disk_read_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk write bytes/s - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(system_disk_write_bytes_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk read IO/s - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "io/s" } },
     "targets": [
      {
       "expr": "irate(system_disk_read_ops_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk write IO/s - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "io/s" } },
     "targets": [
      {
       "expr": "irate(system_disk_write_ops_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk average read time  - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(system_disk_read_weighted_time_seconds_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk average write time  - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(system_disk_write_weighted_time_seconds_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  }
 ]
}